image: docker:19.03.1

stages:
    - dockerize

.build_image: &build_image
    stage: dockerize
    services:
        - docker:dind
    script:
        - cd $IMAGE_NAME
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build --no-cache -t $CI_REGISTRY_IMAGE/$IMAGE_NAME .
        - docker tag $CI_REGISTRY_IMAGE/$IMAGE_NAME $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_JOB_ID
        - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME
    only:
        - master
    when: manual

php7.2:
    <<: *build_image
    variables:
        DOCKER_DRIVER: overlay
        IMAGE_NAME: php-7.2
